version: '3'
services:
  node:
    build:  
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: portifolio
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"